/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.com.lighthouse.sistema.gui;

/**
 *
 * @author oscarreyes
 */
public class master extends javax.swing.JFrame {

    /**
     * Creates new form master
     */
    public master() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup grupModules = new javax.swing.ButtonGroup();
        contenedorModulos = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnPeriodo = new javax.swing.JToggleButton();
        btnCurso = new javax.swing.JToggleButton();
        btnAsignacionCurso = new javax.swing.JToggleButton();
        btnAlumnos = new javax.swing.JToggleButton();
        btnAsignacionAlumnos = new javax.swing.JToggleButton();
        btnPlanificacion = new javax.swing.JToggleButton();
        btnExportarNotas = new javax.swing.JToggleButton();
        btnExportarAlumnos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        grupModules.add(btnPeriodo);
        btnPeriodo.setText("Periodo");
        btnPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodoActionPerformed(evt);
            }
        });

        grupModules.add(btnCurso);
        btnCurso.setText("Cursos");
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        grupModules.add(btnAsignacionCurso);
        btnAsignacionCurso.setText("Asignación Cursos");
        btnAsignacionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionCursoActionPerformed(evt);
            }
        });

        grupModules.add(btnAlumnos);
        btnAlumnos.setText("Alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        grupModules.add(btnAsignacionAlumnos);
        btnAsignacionAlumnos.setText("Asignación Alumnos");
        btnAsignacionAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionAlumnosActionPerformed(evt);
            }
        });

        grupModules.add(btnPlanificacion);
        btnPlanificacion.setText("Planificación");
        btnPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificacionActionPerformed(evt);
            }
        });

        grupModules.add(btnExportarNotas);
        btnExportarNotas.setText("Exportar Notas");
        btnExportarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarNotasActionPerformed(evt);
            }
        });

        grupModules.add(btnExportarAlumnos);
        btnExportarAlumnos.setText("Exportar Alumnos");
        btnExportarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignacionCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignacionAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlanificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExportarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExportarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignacionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignacionAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportarNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExportarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorModulos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorModulos)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PeriodoFrame periodo;
    private void btnPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodoActionPerformed
        // TODO add your handling code here:
        if(periodo == null){
                periodo = new PeriodoFrame();
                contenedorModulos.add(periodo);
                periodo.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(periodo);
            }
    }//GEN-LAST:event_btnPeriodoActionPerformed
    CursosFrame curso;
    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
         //TODO add your handling code here:
        if(curso == null){
                curso = new CursosFrame();
                contenedorModulos.add(curso);
                curso.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(curso);
            }
    }//GEN-LAST:event_btnCursoActionPerformed
    AsignacionCursoFrame asignacionCurso;
    private void btnAsignacionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionCursoActionPerformed
        // TODO add your handling code here:
        if(asignacionCurso == null){
                asignacionCurso = new AsignacionCursoFrame();
                contenedorModulos.add(asignacionCurso);
                asignacionCurso.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(asignacionCurso);
            }
    }//GEN-LAST:event_btnAsignacionCursoActionPerformed
    AlumnosFrame alumno;
    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
        if(alumno == null){
                alumno = new AlumnosFrame();
                contenedorModulos.add(alumno);
                alumno.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(alumno);
            }
    }//GEN-LAST:event_btnAlumnosActionPerformed
    AsignacionAlumnosFrame asignacionAlumnos;
    private void btnAsignacionAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionAlumnosActionPerformed
        // TODO add your handling code here:
        if(asignacionAlumnos == null){
                asignacionAlumnos = new AsignacionAlumnosFrame();
                contenedorModulos.add(asignacionAlumnos);
                asignacionAlumnos.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(asignacionAlumnos);
            }
    }//GEN-LAST:event_btnAsignacionAlumnosActionPerformed
    
    PlanificacionFrame planificacion;
    private void btnPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificacionActionPerformed
        // TODO add your handling code here:
        if(planificacion == null){
                planificacion = new PlanificacionFrame();
                contenedorModulos.add(planificacion);
                planificacion.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(planificacion);
            }
    }//GEN-LAST:event_btnPlanificacionActionPerformed
    ExportarNotasFrame exportarNotas;
    private void btnExportarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarNotasActionPerformed
        // TODO add your handling code here:
        if(exportarNotas == null){
                exportarNotas = new ExportarNotasFrame();
                contenedorModulos.add(exportarNotas);
                exportarNotas.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(exportarNotas);
            }
    }//GEN-LAST:event_btnExportarNotasActionPerformed
    ExportarAlumnosFrame exportarAlumnos;
    private void btnExportarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarAlumnosActionPerformed
        // TODO add your handling code here:
        if(exportarAlumnos == null){
                exportarAlumnos = new ExportarAlumnosFrame();
                contenedorModulos.add(exportarAlumnos);
                exportarAlumnos.setVisible(true);
            }
        else{
                contenedorModulos.getDesktopManager().maximizeFrame(exportarAlumnos);
            }
    }//GEN-LAST:event_btnExportarAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlumnos;
    private javax.swing.JToggleButton btnAsignacionAlumnos;
    private javax.swing.JToggleButton btnAsignacionCurso;
    private javax.swing.JToggleButton btnCurso;
    private javax.swing.JToggleButton btnExportarAlumnos;
    private javax.swing.JToggleButton btnExportarNotas;
    private javax.swing.JToggleButton btnPeriodo;
    private javax.swing.JToggleButton btnPlanificacion;
    private javax.swing.JDesktopPane contenedorModulos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
